### ISSUE TITLE
[Respect] Fantastic! Thank you

### ISSUE THREAD

**Issue by pswilde** [sfonteneau/AzureADConnect_Samba4#14]
Hi,
I just wanted to say thanks for creating this. I'm moving some client servers from MS AD to various Linux/BSD platforms and this is going to help me out massively.
The only one minor thing is my samba sam.ldb is in a different directory to the one in run_sync.py. I can work around it easy enough, it's only two files I have to change, but I was wondering if you'd be interested in a pull request for a change to search a few common samba file locations and/or check a samba config variable (i.e. lock directory) to try to intelligently find the sam.ldb file?

If so, I can add and commit this for your approval.

Thanks again,

**Comment by pswilde** [comment]
Well, I should have read the documentation properly I guess! :rofl: 
That should probably be absolutely fine, ignore me (apart from the massive thank yous!)

**Comment by sfonteneau** [comment]
@pswilde test anyway I haven't tried it ;)

**Comment by pswilde** [comment]
Yep, already have, works perfectly!
Thanks
