### ISSUE TITLE
Directory synchronization off

### ISSUE THREAD

**Issue by kedar-linuxspec** [sfonteneau/AzureADConnect_Samba4#2]
Azure AD is not allowing to switch on user sync to ON from the admin console. The only way it appears is to install Azure Connect  or provisioning client ona  windows server and do a sync. 

Is there a way to switch on the directory sync from the Azure console

**Comment by sfonteneau** [comment]
it seems possible here I will look :

https://github.com/microsoftgeek/Azure-PowerShell/blob/50c068722716384ca816cf00328c17ad19f3f8fd/AADInternals-master/ProvisioningAPI.ps1#L3404

**Comment by sfonteneau** [comment]
I just made a commit that implements the "EnableDirSync" https://github.com/sfonteneau/AADInternals_python/commit/b5d64a9baaa1fa82a8779277d97ce725abbd8e4d always base on the AADInternals project

And implement in sync script :
https://github.com/sfonteneau/AzureADConnect_Samba4/commit/8ce78792a4f40ff55ac5f4b067617495fe2f6923

Can you tell me if it works for you?

**Comment by kedar-linuxspec** [comment]
Oh.. sure.. thanks for your effort :)

**Comment by rajeevsonkhia** [comment]
It throws an below-mentioned error

AttributeError: 'AADInternals' object has no attribute 'set_adsyncenabled

**Comment by sfonteneau** [comment]
The AADInternals submodule has also been updated:

```
cd /opt/sync-azure/AADInternals_python
git pull
```

**Comment by rajeevsonkhia** [comment]
After updating the repo it throws a below error:
python3 /opt/sync-azure/run_sync.py 
enable Ad Sync
enable PasswordHashSync feature
Traceback (most recent call last):
  File "/opt/sync-azure/run_sync.py", line 104, in <module>
    run_sync(force=False)
  File "/opt/sync-azure/run_sync.py", line 46, in run_sync
    azure.enable_password_hash_sync()
  File "/opt/sync-azure/libsync.py", line 79, in enable_password_hash_sync
    self.az.set_sync_features(enable_features=['PasswordHashSync'])
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 251, in set_sync_features
    current_features = self.get_syncconfiguration()['DirSyncFeatures']
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 47, in get_syncconfiguration
    "AnchorAttribute" :                             data["DirSyncConfiguration"]["AnchorAttribute"],
KeyError: 'AnchorAttribute'

**Comment by sfonteneau** [comment]
I just did a test with a new instance that has never seen  "microsoft azure ad connect"

Indeed some parameters are missing which makes the script crash

correct here normally :
https://github.com/sfonteneau/AADInternals_python/commit/6a3d1e0dcfbd99b803cfda46d67b87d013ab509f

The AADInternals submodule has also been updated (again)

**Comment by rajeevsonkhia** [comment]
After pulling the update and running the script it throws below error:
Traceback (most recent call last):
  File "/opt/sync-azure/run_sync.py", line 104, in <module>
    run_sync(force=False)
  File "/opt/sync-azure/run_sync.py", line 75, in run_sync
    azure.generate_all_dict()
  File "/opt/sync-azure/libsync.py", line 108, in generate_all_dict
    for group in self.az.list_groups():
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 478, in list_groups
    dict_cloudanchor_sourceanchor = self.get_dict_cloudanchor_sourceanchor()
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 458, in get_dict_cloudanchor_sourceanchor
    for entry in self.get_syncobjects(False):
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 506, in get_syncobjects
    return  self.xml_to_result(response,command)['b:ResultObjects']['b:AzureADSyncObject']
TypeError: 'NoneType' object is not subscriptable

**Comment by sfonteneau** [comment]
https://github.com/sfonteneau/AADInternals_python/commit/9b3ae15bb7c6ca30d71418abd2296187d55aedfa

and now 

on your previous test the creation has already worked I guess

**Comment by rajeevsonkhia** [comment]
Yes, it worked.

**Comment by rajeevsonkhia** [comment]
if the change password option is enabled for the user on the AD and the script runs in the background then it will fail. 
Below is the error
Traceback (most recent call last):
  File "/opt/sync-azure/run_sync.py", line 104, in <module>
    run_sync(force=False)
  File "/opt/sync-azure/run_sync.py", line 93, in run_sync
    azure.send_hashnt(smb.dict_id_hash[entry],entry)
  File "/opt/sync-azure/libsync.py", line 117, in send_hashnt
    self.az.set_userpassword(hashnt=hashnt,sourceanchor=sourceanchor)
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 551, in set_userpassword
    raise Exception(formatresponse.get('b:ExtendedErrorInformation',formatresponse))
Exception: {'b:CloudAnchor': {'@i:nil': 'true'}, 'b:Result': '2', 'b:SourceAnchor': 'S-1-5-21-3802977416-4012356894-2710300367-1105'}

But as soon you set the password the sync works without any error.

**Comment by sfonteneau** [comment]
Can you open a new topic on github? Mixing requests complicates the discussion ?
